### ISSUE TITLE
검색 기능이 있었으면 좋겠어요!

### ISSUE THREAD

**Issue by asrahi** [yeonjuan/whale-extension-emoji-picker#39]
이모지 피커 너무 잘 쓰고 있는데 검색 기능이 없어서 아쉬워요
검색기능이 있었으면 좋겠어요!

**Comment by yeonjuan** [comment]
안녕하세요 @asrahi :) 처음 들어온 요청이네요. 감사합니다. 검색 기능을 추가해 보겠습니다. 👍

**Comment by yeonjuan** [comment]
기능 추가하고 배포 되었습니다~
