### ISSUE TITLE
토스트 메시지 애니메이션 개선

### ISSUE THREAD

**Issue by tmdgus0084** [yeonjuan/whale-extension-emoji-picker#7]
좋은 프로젝트 감사합니다. 토스트 메시지 애니메이션에 개선이 필요할 것 같아요.

기존에는
- 토스트 필드에 텍스트 출력
- 올라가는 애니메이션 재생
- 대기
- **텍스트 사라짐**
- 내려가는 애니메이션 재생

인 것 같은데 이렇게 하면 토스트 메시지가 사라지는 애니메이션에서 아무런 텍스트도 안보이니 애니메이션이 부자연스러워 보입니다. 텍스트가 애니메이션이 끝난 시점에 사라지게 하거나 유지하면 좋을 것 같아요!

**Comment by yeonjuan** [comment]
@tmdgus0084 좋은 피드백 감사합니다~. 다음번에 반영하도록 하겠습니다
